name: Benchmark

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/benchmark.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Run at midnight UTC every Sunday

jobs:
  benchmark:
    name: Performance Benchmark
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'
        cache: true
    
    - name: Install dependencies
      run: go mod download
    
    - name: Run benchmarks
      run: |
        mkdir -p benchmark-results
        
        # Run benchmarks for each provider module
        for dir in cache config http log middleware; do
          if [ -d "$dir" ]; then
            echo "Running benchmarks for $dir"
            cd $dir
            go test -bench=. -benchmem -run=^$ -benchtime=1s ./... | tee ../benchmark-results/$dir.txt
            cd ..
          fi
        done
    
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'go'
        output-file-path: benchmark-results/*.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        comment-on-alert: true
        fail-on-alert: false
        alert-threshold: '150%'
        comment-always: false
